### ISSUE TITLE
Page flip animation

### ISSUE THREAD

**Issue by Bashamega** [Bashamega/ebookCraft#12]
Hello:)
This feature request is making the page flip to give the user the experience of turning pages on a real book.

**Comment by Chandrika11P11** [comment]
Would you please assign me to this issue ?
I would love to work on it.

And I want your thoughts on following ideas: 
1. Two pages view with one page being flipped to the other side.
2. Book-like styling to the pages.

**Comment by Bashamega** [comment]
> Would you please assign me to this issue ? I would love to work on it.
> 
> And I want your thoughts on following ideas:
> 
> 1. Two pages view with one page being flipped to the other side.
> 2. Book-like styling to the pages.

Great assigned to you

**Comment by Bashamega** [comment]
@Chandrika11P11 Please create a pr

**Comment by Shubh8899** [comment]
Hey @Bashamega  I would like to work on this one, can you assign it to me?

**Comment by Bashamega** [comment]
> Hey @Bashamega I would like to work on this one, can you assign it to me?

sure

**Comment by Shubh8899** [comment]
@Bashamega  would it okay to use this [page-flip](https://www.npmjs.com/package/react-pageflip)

**Comment by Bashamega** [comment]
> @Bashamega would it okay to use this [page-flip](https://www.npmjs.com/package/react-pageflip)

Sure, the library looks great

**Comment by vr-varad** [comment]
@Shubh8899 are u still working on this issue?

**Comment by sagarhedaoo** [comment]
Hi @Bashamega Can I start working on this?

**Comment by Bashamega** [comment]
> Hi @Bashamega Can I start working on this?

Sure

**Comment by sagarhedaoo** [comment]
@Bashamega Is there any particular node version that should be used to install dependencies? Because I am not able to proceed further with "npm install"

**Comment by Bashamega** [comment]
> @Bashamega Is there any particular node version that should be used to install dependencies? Because I am not able to proceed further with "npm install"

It should work can you paste the error?

**Comment by sagarhedaoo** [comment]
> > @Bashamega Is there any particular node version that should be used to install dependencies? Because I am not able to proceed further with "npm install"
> 
> It should work can you paste the error?

sagarhedaoo@Sagars-MBP ebookCraft % npm install
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated npmlog@6.0.2: This package is no longer supported.
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported
npm WARN deprecated gauge@4.0.4: This package is no longer supported.
npm ERR! code 1
npm ERR! path /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Binary found at /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/vendor/darwin-arm64-108/binding.node
npm ERR! Testing binary
npm ERR! Binary has a problem: Error: dlopen(/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/vendor/darwin-arm64-108/binding.node, 0x0001): tried: '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/vendor/darwin-arm64-108/binding.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/vendor/darwin-arm64-108/binding.node' (no such file), '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/vendor/darwin-arm64-108/binding.node' (not a mach-o file)
npm ERR!     at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1119:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:960:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1143:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
npm ERR!     at module.exports (/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/lib/binding.js:19:10)
npm ERR!     at Object.<anonymous> (/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/lib/index.js:13:35)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1256:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1119:32) {
npm ERR!   code: 'ERR_DLOPEN_FAILED'
npm ERR! }
npm ERR! Building the binary locally
npm ERR! Building: /Users/sagarhedaoo/.nvm/versions/node/v18.17.0/bin/node /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/Users/sagarhedaoo/.nvm/versions/node/v18.17.0/bin/node',
npm ERR! gyp verb cli   '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@18.17.0 | darwin | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/opt/homebrew/opt/python@3.12/bin/python3.12"
npm ERR! gyp verb find Python - executing "/opt/homebrew/opt/python@3.12/bin/python3.12" to get version
npm ERR! gyp verb find Python - version is "3.12.3"
npm ERR! gyp info find Python using Python version 3.12.3 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 18.17.0
npm ERR! gyp verb command install [ '18.17.0' ]
npm ERR! gyp verb install input version string "18.17.0"
npm ERR! gyp verb install installing version: 18.17.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 18.17.0
npm ERR! gyp verb build dir attempting to create "build" dir: /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? Yes
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/sagarhedaoo/Library/Caches/node-gyp/18.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/sagarhedaoo/Library/Caches/node-gyp/18.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/sagarhedaoo/Library/Caches/node-gyp/18.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 23.5.0
npm ERR! gyp ERR! command "/Users/sagarhedaoo/.nvm/versions/node/v18.17.0/bin/node" "/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass
npm ERR! gyp ERR! node -v v18.17.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

**Comment by Bashamega** [comment]
> > > @Bashamega Is there any particular node version that should be used to install dependencies? Because I am not able to proceed further with "npm install"
> > 
> > 
> > It should work can you paste the error?
> 
> sagarhedaoo@Sagars-MBP ebookCraft % npm install npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful. npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs npm WARN deprecated npmlog@6.0.2: This package is no longer supported. npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported npm WARN deprecated are-we-there-yet@3.0.1: This package is no longer supported. npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported npm WARN deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported npm WARN deprecated gauge@4.0.4: This package is no longer supported. npm ERR! code 1 npm ERR! path /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass npm ERR! command failed npm ERR! command sh -c node scripts/build.js npm ERR! Binary found at /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/vendor/darwin-arm64-108/binding.node npm ERR! Testing binary npm ERR! Binary has a problem: Error: dlopen(/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/vendor/darwin-arm64-108/binding.node, 0x0001): tried: '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/vendor/darwin-arm64-108/binding.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/vendor/darwin-arm64-108/binding.node' (no such file), '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/vendor/darwin-arm64-108/binding.node' (not a mach-o file) npm ERR! at Module._extensions..node (node:internal/modules/cjs/loader:1340:18) npm ERR! at Module.load (node:internal/modules/cjs/loader:1119:32) npm ERR! at Module._load (node:internal/modules/cjs/loader:960:12) npm ERR! at Module.require (node:internal/modules/cjs/loader:1143:19) npm ERR! at require (node:internal/modules/cjs/helpers:110:18) npm ERR! at module.exports (/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/lib/binding.js:19:10) npm ERR! at Object. (/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/lib/index.js:13:35) npm ERR! at Module._compile (node:internal/modules/cjs/loader:1256:14) npm ERR! at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) npm ERR! at Module.load (node:internal/modules/cjs/loader:1119:32) { npm ERR! code: 'ERR_DLOPEN_FAILED' npm ERR! } npm ERR! Building the binary locally npm ERR! Building: /Users/sagarhedaoo/.nvm/versions/node/v18.17.0/bin/node /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library= npm ERR! gyp info it worked if it ends with ok npm ERR! gyp verb cli [ npm ERR! gyp verb cli '/Users/sagarhedaoo/.nvm/versions/node/v18.17.0/bin/node', npm ERR! gyp verb cli '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/bin/node-gyp.js', npm ERR! gyp verb cli 'rebuild', npm ERR! gyp verb cli '--verbose', npm ERR! gyp verb cli '--libsass_ext=', npm ERR! gyp verb cli '--libsass_cflags=', npm ERR! gyp verb cli '--libsass_ldflags=', npm ERR! gyp verb cli '--libsass_library=' npm ERR! gyp verb cli ] npm ERR! gyp info using node-gyp@8.4.1 npm ERR! gyp info using node@18.17.0 | darwin | arm64 npm ERR! gyp verb command rebuild [] npm ERR! gyp verb command clean [] npm ERR! gyp verb clean removing "build" directory npm ERR! gyp verb command configure [] npm ERR! gyp verb find Python Python is not set from command line or npm configuration npm ERR! gyp verb find Python Python is not set from environment variable PYTHON npm ERR! gyp verb find Python checking if "python3" can be used npm ERR! gyp verb find Python - executing "python3" to get executable path npm ERR! gyp verb find Python - executable path is "/opt/homebrew/opt/python@3.12/bin/python3.12" npm ERR! gyp verb find Python - executing "/opt/homebrew/opt/python@3.12/bin/python3.12" to get version npm ERR! gyp verb find Python - version is "3.12.3" npm ERR! gyp info find Python using Python version 3.12.3 found at "/opt/homebrew/opt/python@3.12/bin/python3.12" npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 18.17.0 npm ERR! gyp verb command install [ '18.17.0' ] npm ERR! gyp verb install input version string "18.17.0" npm ERR! gyp verb install installing version: 18.17.0 npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed npm ERR! gyp verb install version is already installed, need to check "installVersion" npm ERR! gyp verb got "installVersion" 9 npm ERR! gyp verb needs "installVersion" 9 npm ERR! gyp verb install version is good npm ERR! gyp verb get node dir target node version installed: 18.17.0 npm ERR! gyp verb build dir attempting to create "build" dir: /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/build npm ERR! gyp verb build dir "build" dir needed to be created? Yes npm ERR! gyp verb build/config.gypi creating config file npm ERR! gyp verb build/config.gypi writing out config file: /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/build/config.gypi npm ERR! gyp verb config.gypi checking for gypi file: /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/config.gypi npm ERR! gyp verb common.gypi checking for gypi file: /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/common.gypi npm ERR! gyp verb gyp gyp format was not specified; forcing "make" npm ERR! gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12 npm ERR! gyp info spawn args [ npm ERR! gyp info spawn args '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/gyp/gyp_main.py', npm ERR! gyp info spawn args 'binding.gyp', npm ERR! gyp info spawn args '-f', npm ERR! gyp info spawn args 'make', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass/build/config.gypi', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/addon.gypi', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/Users/sagarhedaoo/Library/Caches/node-gyp/18.17.0/include/node/common.gypi', npm ERR! gyp info spawn args '-Dlibrary=shared_library', npm ERR! gyp info spawn args '-Dvisibility=default', npm ERR! gyp info spawn args '-Dnode_root_dir=/Users/sagarhedaoo/Library/Caches/node-gyp/18.17.0', npm ERR! gyp info spawn args '-Dnode_gyp_dir=/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp', npm ERR! gyp info spawn args '-Dnode_lib_file=/Users/sagarhedaoo/Library/Caches/node-gyp/18.17.0/<(target_arch)/node.lib', npm ERR! gyp info spawn args '-Dmodule_root_dir=/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass', npm ERR! gyp info spawn args '-Dnode_engine=v8', npm ERR! gyp info spawn args '--depth=.', npm ERR! gyp info spawn args '--no-parallel', npm ERR! gyp info spawn args '--generator-output', npm ERR! gyp info spawn args 'build', npm ERR! gyp info spawn args '-Goutput_dir=.' npm ERR! gyp info spawn args ] npm ERR! Traceback (most recent call last): npm ERR! File "/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/gyp/gyp_main.py", line 42, in npm ERR! import gyp # noqa: E402 npm ERR! ^^^^^^^^^^ npm ERR! File "/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/gyp/pylib/gyp/**init**.py", line 9, in npm ERR! import gyp.input npm ERR! File "/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in npm ERR! from distutils.version import StrictVersion npm ERR! ModuleNotFoundError: No module named 'distutils' npm ERR! gyp ERR! configure error npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1 npm ERR! gyp ERR! stack at ChildProcess.onCpExit (/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/lib/configure.js:259:16) npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:514:28) npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:291:12) npm ERR! gyp ERR! System Darwin 23.5.0 npm ERR! gyp ERR! command "/Users/sagarhedaoo/.nvm/versions/node/v18.17.0/bin/node" "/Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library=" npm ERR! gyp ERR! cwd /Users/sagarhedaoo/Downloads/ebookCraft/node_modules/node-sass npm ERR! gyp ERR! node -v v18.17.0 npm ERR! gyp ERR! node-gyp -v v8.4.1 npm ERR! gyp ERR! not ok npm ERR! Build failed with error code: 1

I think the problem is with your setup, because i have tried it and it worked. I also works on gitpod

**Comment by vishesh-hue** [comment]
fixed #12
