### ISSUE TITLE
Potential UI/UX Improvements for Your Website

### ISSUE THREAD

**Issue by diip3sh** [Bashamega/ebookCraft#22]
Hi, There I didn't get any idea from what the site is for but I found some bugs and some UI error so to just inform you:

Specific Observations:

**Text Focus**:The wording on the website appears to be out of focus or lacking clarity.
**Alignment**: The title and body text are not centered or aligned consistently.
**Navigation Flow:** The current navigation system requires users to utilize the "back" button to navigate forward, which may be counterintuitive.
**Hover Effect**: The hover effect on the "back" icon could be enhanced with padding to improve visual appeal.

I am interested in contributing to the improvement of your website. If these observations are documented as new issues or sub-issues within your existing system, I would be happy to assist in making the site more user-friendly and visually appealing.
![240423_11h40m40s_screenshot](https://github.com/Bashamega/ebookCraft/assets/99866329/8f77a62a-9d6d-47b4-9949-ef3cb86524eb)

**Comment by Bashamega** [comment]
Hello:)
I would love that.

For context the website is for creating ebooks by just writing html.

**Comment by diip3sh** [comment]
Ok but I didn't saw any input for adding the html or is it work in progress ?

**Comment by Bashamega** [comment]
> Ok but I didn't saw any input for adding the html or is it work in progress ?

No, To create an input you create html files in the `public/pages` folder, which generates the ebook
