### ISSUE TITLE
negative number in page number input by double clicking on left arrow

### ISSUE THREAD

**Issue by DevEliasKh** [Bashamega/ebookCraft#26]
Hi
this issue happen if you double click on left arrow when the number is '2'.
left arrow is disable when the page number is '1' so user can't make it less than 1 but if page number '2' by double clicking page number can be negative
![image](https://github.com/Bashamega/ebookCraft/assets/20316165/b954e5e6-ba16-414a-8d1f-a37cfbc30127)
I work on it so please assign it to me

**Comment by Bashamega** [comment]
Sure

**Comment by DevEliasKh** [comment]
> Sure

there is  problem when installing package with `npm i`
error :
```
npm error code 1
npm error path *my-path*/ebookCraft/node_modules/node-sass
npm error command failed
npm error command sh -c node scripts/build.js
```
there is something wrong with node-sass

**Comment by Bashamega** [comment]
> > Sure
> 
> there is problem when installing package with `npm i` error :
> 
> ```
> npm error code 1
> npm error path *my-path*/ebookCraft/node_modules/node-sass
> npm error command failed
> npm error command sh -c node scripts/build.js
> ```
> 
> there is something wrong with node-sass

We deployed it yesterday and it was working.
Make sure that you have the latest version of node and npm or your package manager
