### ISSUE TITLE
Add documentation pages

### ISSUE THREAD

**Issue by Bashamega** [Bashamega/ebookCraft#9]
Create multiple pages for documentation, by creating multiple html files and adding an about, and how to create an e-book with ebbook-Craft.

**Comment by drewduong** [comment]
Can you please assign this to me? Thank you!

**Comment by Bashamega** [comment]
> Can you please assign this to me? Thank you!

Sure.
If you have any questions you can ask

**Comment by Bashamega** [comment]
@drewduong Please create a pr
